export type PopularMovieResult = {
  page: number;
  results: MovieResult[];
  total_pages: number;
  total_results: number;
};

export type MovieResult = {
  adult: boolean;
  backdrop_path: string;
  genre_ids: number[];
  id: number;
  original_language: OriginalLanguage;
  original_title: string;
  overview: string;
  popularity: number;
  poster_path: string;
  release_date: string;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
};

export enum OriginalLanguage {
  De = "de",
  En = "en",
  Fr = "fr",
  Ko = "ko",
}

// Generated by https://quicktype.io

export type PopularTVShowResult = {
  page: number;
  results: TVShowResult[];
  total_pages: number;
  total_results: number;
};

export type TVShowResult = {
  backdrop_path: string;
  first_air_date: string;
  genre_ids: number[];
  id: number;
  name: string;
  origin_country: string[];
  original_language: OriginalLanguage;
  original_name: string;
  overview: string;
  popularity: number;
  poster_path: string;
  vote_average: number;
  vote_count: number;
};
